moviedat/config/routes.rb
Rails.application.routes.draw do
  resources :titles
  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

moviedat/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

moviedat/app/models/title.rb
class Title < ApplicationRecord
end

moviedat/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

moviedat/app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  before_action :set_title, only: [:show, :edit, :update, :destroy]

  # GET /titles
  # GET /titles.json
  def index
    @titles = Title.all
  end

  # GET /titles/1
  # GET /titles/1.json
  def show
  end

  # GET /titles/new
  def new
    @title = Title.new
  end

  # GET /titles/1/edit
  def edit
  end

  # POST /titles
  # POST /titles.json
  def create
    @title = Title.new(title_params)

    respond_to do |format|
      if @title.save
        format.html { redirect_to @title, notice: 'Title was successfully created.' }
        format.json { render :show, status: :created, location: @title }
      else
        format.html { render :new }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /titles/1
  # PATCH/PUT /titles/1.json
  def update
    respond_to do |format|
      if @title.update(title_params)
        format.html { redirect_to @title, notice: 'Title was successfully updated.' }
        format.json { render :show, status: :ok, location: @title }
      else
        format.html { render :edit }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /titles/1
  # DELETE /titles/1.json
  def destroy
    @title.destroy
    respond_to do |format|
      format.html { redirect_to titles_url, notice: 'Title was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_title
      @title = Title.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def title_params
      params.require(:title).permit(:cast, :plat, :movie_url, :poster_url)
    end
end

moviedat/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

moviedat/app/helpers/application_helper.rb
module ApplicationHelper
end

moviedat/app/helpers/titles_helper.rb
module TitlesHelper
end

moviedat/app/helpers/welcome_helper.rb
module WelcomeHelper
end

moviedat/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

moviedat/app/views/titles/_form.html.erb
<%= form_with(model: title, local: true) do |form| %>
  <% if title.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(title.errors.count, "error") %> prohibited this title from being saved:</h2>

      <ul>
      <% title.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cast %>
    <%= form.text_field :cast, id: :title_cast %>
  </div>

  <div class="field">
    <%= form.label :plat %>
    <%= form.text_area :plat, id: :title_plat %>
  </div>

  <div class="field">
    <%= form.label :movie_url %>
    <%= form.text_field :movie_url, id: :title_movie_url %>
  </div>

  <div class="field">
    <%= form.label :poster_url %>
    <%= form.text_field :poster_url, id: :title_poster_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

moviedat/app/views/titles/edit.html.erb
<h1>Editing Title</h1>

<%= render 'form', title: @title %>

<%= link_to 'Show', @title %> |
<%= link_to 'Back', titles_path %>

moviedat/app/views/titles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Titles</h1>

<table>
  <thead>
    <tr>
      <th>Cast</th>
      <th>Plat</th>
      <th>Movie url</th>
      <th>Poster url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @titles.each do |title| %>
      <tr>
        <td><%= title.cast %></td>
        <td><%= title.plat %></td>
        <td><%= title.movie_url %></td>
        <td><%= title.poster_url %></td>
        <td><%= link_to 'Show', title %></td>
        <td><%= link_to 'Edit', edit_title_path(title) %></td>
        <td><%= link_to 'Destroy', title, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Title', new_title_path %>

moviedat/app/views/titles/new.html.erb
<h1>New Title</h1>

<%= render 'form', title: @title %>

<%= link_to 'Back', titles_path %>

moviedat/app/views/titles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cast:</strong>
  <%= @title.cast %>
</p>

<p>
  <strong>Plat:</strong>
  <%= @title.plat %>
</p>

<p>
  <strong>Movie url:</strong>
  <%= @title.movie_url %>
</p>

<video width="320" height="240" controls>
  <source src="<%= @title.movie_url %>" type="video/mp4">

</video>

<p>
  <strong>Poster url:</strong>
  <%= @title.poster_url %>
</p>

<%= link_to 'Edit', edit_title_path(@title) %> |
<%= link_to 'Back', titles_path %>

moviedat/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<div class="login-box">
  <div class="row collapse expanded">
    <div class="small-12 medium-6 column small-order-2 medium-order-1">
      <div class="login-box-form-section">
        <h1 class="login-box-title">Sign up</h1>
        <input class="login-box-input" type="text" name="username" placeholder="Username" />
        <input class="login-box-input" type="email" name="email" placeholder="E-mail" />
        <input class="login-box-input" type="password" name="password" placeholder="Password" />
        <input class="login-box-input" type="password" name="password2" placeholder="Retype password" />
        <input class="login-box-submit-button" type="submit" name="signup_submit" value="Sign me up" />
      </div>
      <div class="or">OR</div>
    </div>
    <div class="small-12 medium-6 column small-order-1 medium-order-2 login-box-social-section">
      <div class="login-box-social-section-inner">
        <span class="login-box-social-headline">Sign in with<br />your social network</span>
        <a class="login-box-social-button-facebook">Log in with facebook</a>
        <a class="login-box-social-button-twitter">Log in with Twitter</a>
        <a class="login-box-social-button-google">Log in with Google+</a>
      </div>
    </div>
  </div>
</div>